name: asgat
channels:
  - rusty1s
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - cudatoolkit=11.1.74
  - cvxpy=1.1.15
  - cvxpy-base=1.1.15
  - decorator=4.4.2
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - googledrivedownloader=0.4
  - idna=3.1
  - intel-openmp=2021.3.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=11.1.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - networkx=2.5.1
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - osqp=0.6.2
  - pandas=1.3.0
  - pillow=8.3.1
  - pip=21.2.2
  - pycparser=2.20
  - pygsp=0.5.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.11
  - python-dateutil=2.8.2
  - python-louvain=0.15
  - python_abi=3.7
  - pytorch=1.9.0
  - pytorch-cluster=1.5.9
  - pytorch-geometric=1.7.2
  - pytorch-scatter=2.0.8
  - pytorch-sparse=0.6.11
  - pytorch-spline-conv=1.2.1
  - pytz=2021.1
  - qdldl-python=0.1.5
  - readline=8.1
  - requests=2.26.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - scs=2.1.4
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm=4.62.1
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cvxpylayers==0.1.5
    - diffcp==1.0.17
    - ecos==2.0.7.post1
    - pybind11==2.7.1
