name: asgat
channels:
  - conda-forge
  - rusty1s
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - torchvision
  - pytorch
  - torchaudio
  - pytorch-geometric
  - pygsp
  - cvxpy
  - pip
  - pip:
    - cvxpylayers==0.1.5
    - pybind11==2.6.2
